apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test
  namespace: xiaomo
spec:
  rules:
    - host: k8s.xiaomo.info
      http:
        paths:
          - backend:
              service:
                name: nginx-svc


